export const tempData = [
  {
    id: "1",
    qns: "Discuss the concept of linear separability. Explain a problem which is not linear separable.",
    level: "Comprehension",
    part: "A",
    module: 1,
    mark: 10,
  },
  {
    id: "2",
    qns: "Obtain the output of the neuron for a network with inputs are given as [x1,x2,x3] = [0.8,0.6,0.4] and the weights are [w1,w2,w3] = [0.1,0.3,-0.2] with bias = 0.35. Also find the output for: i) Binary sigmoidal ii) Bipolar sigmoidal activation functions.",
    level: "Comprehension",
    part: "A",
    module: 2,
    mark: 3,
  },
  {
    id: "3",
    qns: "Explain the different learning mechanisms used in artificial neural networks with the help of necessary diagrams.",
    level: "Comprehension",
    part: "A",
    module: 1,
    mark: 4,
  },
  {
    id: "4",
    qns: "Design a Hebb net to implement NOR function with:i) Bipolar inputs and targets ii) Bipolar inputs and binary targets",
    level: "Application",
    part: "A",
    module: 2,
    mark: 3,
  },
  {
    id: "5",
    qns: "Using Hebb rule calculate the weights required to perform following classification. The vectors (1,1,1,1) and (-1,1,-1,-1) are members of the class (and therefore have the target value 1); vectors (1,1,1,-1) and (1,-1,-1,1) are not members of the class (and have the target value -1).",
    level: "Application",
    part: "A",
    module: 2,
    mark: 3,
  },
  {
    id: "6",
    qns: "Implement logical AND function using binary inputs and bipolar targets without bias up to 2 epochs. Take first with (0,0) and next without (0,0).",
    level: "Application",
    part: "B",
    module: 2,
    mark: 4,
  },
  {
    id: "7",
    qns: "Implement logical OR function using binary inputs and bipolar targets without bias up to 2 epochs.",
    level: "Application",
    part: "B",
    module: 3,
    mark: 5,
  },

  {
    id: "8",
    qns: "Represent standard fuzzy operations with Venn diagrams. ",
    level: "Comprehension",
    part: "B",
    module: 3,
    mark: 5,
  },
  {
    id: "9",
    qns: "State the conditions for fuzzy tolerance relations.",
    level: "Analysis",
    part: "B",
    module: 2,
    mark: 4,
  },
  {
    id: "10",
    qns: "Differentiate between a) Convex and Non convex fuzzy set b) Normal and Subnormal fuzzy set",
    level: "Comprehension",
    part: "B",
    module: 3,
    mark: 5,
  },
  {
    id: "11",
    qns: "Using inference approach, find the membership values for each of the triangular shapes (I~,R~,E~,IR~) with angles 20⁰ , 40⁰ , 120⁰",
    level: "Application",
    part: "C",
    module: 1,
    mark: 4,
  },
  {
    id: "12",
    qns: "Explain any two defuzzification methods. ",
    level: "Comprehension",
    part: "C",
    module: 2,
    mark: 5,
  },

  {
    id: "13",
    qns: "Explain the features of fuzzy membership function with proper diagram",
    level: "Comprehension",
    part: "C",
    module: 3,
    mark: 5,
  },
];
